server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/security
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  security:
    user:
      name: root
      password: root
    oauth2:
      client:
        registration:
          google:
            client-id: 1084365769783-rtajot9n7nul1i4nql5orbap74a6cpd0.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
logging:
  level:
    root: debug